# Generated by Django 3.2.5 on 2021-08-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kakao', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
                ('birthday', models.DateField(null=True)),
                ('thumbnail', models.CharField(max_length=2000)),
                ('is_host', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
